
services:
  database:
    container_name: database
    hostname: ${DATABASE_HOST}
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - database-vol:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: webapp
    environment:
      FINNHUB_API_KEY: ${FINNHUB_API_KEY}
    ports:
      - '3000:3000'
    depends_on:
      - database

volumes:
  database-vol: